name: karoprod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - numpy 
  - pandas
  - scikit-learn
  - matplotlib
  - ipywidgets
  - optuna
  - pip:
    - tensorflow